"""course and course type added

Revision ID: 1d064058cab7
Revises: 381ed214a22b
Create Date: 2024-09-29 01:17:39.772951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d064058cab7'
down_revision: Union[str, None] = '381ed214a22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_type',
    sa.Column('course_type_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('course_type_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('course_type_id')
    )
    op.create_index(op.f('ix_course_type_course_type_id'), 'course_type', ['course_type_id'], unique=False)
    op.create_table('course',
    sa.Column('course_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('course_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('course_file_pdf', sa.TEXT(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('course_type_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_type.course_type_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_course_course_id'), 'course', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_course_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_course_type_course_type_id'), table_name='course_type')
    op.drop_table('course_type')
    # ### end Alembic commands ###
