"""course and course type relationship updated

Revision ID: 5adb2bdff4ca
Revises: 1d064058cab7
Create Date: 2024-10-05 01:20:00.214573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adb2bdff4ca'
down_revision: Union[str, None] = '1d064058cab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
