"""removed address from subscription model

Revision ID: 6e637db4aa47
Revises: a6355594e540
Create Date: 2024-10-26 11:15:19.942097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e637db4aa47'
down_revision: Union[str, None] = 'a6355594e540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_subscriptions', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_subscriptions', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
