"""course description attribute added

Revision ID: a32cb9e72f4e
Revises: 5adb2bdff4ca
Create Date: 2024-10-12 22:55:09.100438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32cb9e72f4e'
down_revision: Union[str, None] = '5adb2bdff4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_description', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'course_description')
    # ### end Alembic commands ###
