"""removed name on card from subscription model

Revision ID: a6355594e540
Revises: d1727c4f9d5e
Create Date: 2024-10-26 11:13:50.661033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6355594e540'
down_revision: Union[str, None] = 'd1727c4f9d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_subscriptions', 'name_on_card')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_subscriptions', sa.Column('name_on_card', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
