"""course description attribute constraint updated

Revision ID: aa117e14c548
Revises: a32cb9e72f4e
Create Date: 2024-10-12 22:56:51.789897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa117e14c548'
down_revision: Union[str, None] = 'a32cb9e72f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_file_pdf',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_file_pdf',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
