"""set session id to unique

Revision ID: ab1b0b8a6e88
Revises: e9097846f26a
Create Date: 2024-11-02 02:34:36.273000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1b0b8a6e88'
down_revision: Union[str, None] = 'e9097846f26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_course_subscriptions', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_course_subscriptions', type_='unique')
    # ### end Alembic commands ###
