"""subscription model added

Revision ID: d1727c4f9d5e
Revises: aa117e14c548
Create Date: 2024-10-26 01:41:25.052065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1727c4f9d5e'
down_revision: Union[str, None] = 'aa117e14c548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_subscriptions',
    sa.Column('course_subscription_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('name_on_card', sa.TEXT(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('course_subscription_id')
    )
    op.create_index(op.f('ix_user_course_subscriptions_course_subscription_id'), 'user_course_subscriptions', ['course_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_course_subscriptions_course_subscription_id'), table_name='user_course_subscriptions')
    op.drop_table('user_course_subscriptions')
    # ### end Alembic commands ###
