"""delete cascade added to subs model

Revision ID: e0dabfa5ff78
Revises: ab1b0b8a6e88
Create Date: 2024-11-10 16:49:22.735574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dabfa5ff78'
down_revision: Union[str, None] = 'ab1b0b8a6e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_course_subscriptions_course_id_fkey', 'user_course_subscriptions', type_='foreignkey')
    op.drop_constraint('user_course_subscriptions_user_id_fkey', 'user_course_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_course_subscriptions', 'course', ['course_id'], ['course_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_course_subscriptions', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_course_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'user_course_subscriptions', type_='foreignkey')
    op.create_foreign_key('user_course_subscriptions_user_id_fkey', 'user_course_subscriptions', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('user_course_subscriptions_course_id_fkey', 'user_course_subscriptions', 'course', ['course_id'], ['course_id'])
    # ### end Alembic commands ###
