"""stripe session id added

Revision ID: e9097846f26a
Revises: 6e637db4aa47
Create Date: 2024-11-01 01:27:25.891234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9097846f26a'
down_revision: Union[str, None] = '6e637db4aa47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_subscriptions', sa.Column('stripe_session_id', sa.VARCHAR(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_subscriptions', 'stripe_session_id')
    # ### end Alembic commands ###
