"""password reset otp added

Revision ID: f1a2b3c4d5e6
Revises: e0dabfa5ff78
Create Date: 2026-06-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'e0dabfa5ff78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_otp', sa.VARCHAR(length=6), nullable=True))
    op.add_column('user', sa.Column('reset_otp_expiry', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_otp_expiry')
    op.drop_column('user', 'reset_otp')
    # ### end Alembic commands ###
